config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :beer_clubs

  resources :beers

  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  get 'places', to: 'places#index'
  post 'places', to: 'places#search'

  resources :places, only:[:index, :show]

  post 'places', to:'places#search'

  root 'breweries#index'

  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_banned', on: :member
  end
  resources :memberships, only: [:new, :create, :destroy] do
    post 'confirm', on: :member
  end

  get 'beerlist', to:'beers#list'

  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to:'breweries#list'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'
end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships
  has_many :confirmed_memberships, -> {where confirmed: true}, class_name: "Membership"
  has_many :unconfirmed_memberships, -> {where confirmed: [false, nil]}, class_name: "Membership"
  has_many :members, through: :memberships, source: :user
  has_many :confirmed_members, through: :confirmed_memberships, source: :user
  has_many :unconfirmed_members, through: :unconfirmed_memberships, source: :user


  def to_s
    "#{self.name}  | #{self.city}"
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_is_admin, only: [:destroy]


  def index
    @beer_clubs = BeerClub.all
  end

  def show
    if current_user
      if @beer_club.members.include?(current_user)
        @membership = @beer_club.memberships.find_by user_id: current_user.id
      else
        @membership = Membership.new
        @membership.beer_club = @beer_club
      end
      @unconfirmed_members = @beer_club.unconfirmed_members
    end
    @confirmed_members = @beer_club.confirmed_members
  end

  def new
    @beer_club = BeerClub.new
  end

  def edit
  end

  def create
    @beer_club = BeerClub.new(beer_club_params)
    respond_to do |format|
      if @beer_club.save
        Membership.create user_id: current_user.id, beer_club_id: @beer_club.id, confirmed: true
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-info'%>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club, class:'btn btn-info' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('New Beer Club', new_beer_club_path, class:'btn btn-primary') if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path, class: 'btn btn-default'%>

app/views/beer_clubs/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @beer_club.name %>
</p>

<p>
  <strong>Founded:</strong>
  <%= @beer_club.founded %>
</p>

<p>
  <strong>City:</strong>
  <%= @beer_club.city %>
</p>
<h3>Members</h3>
<p>
  <% @confirmed_members.each do |member| %>
    <li><%= link_to member.username, member %></li>
<% end %>
</p>

<% if current_user %>
    <% if @beer_club.members.include?(current_user) %>
        <% if @membership.confirmed %>
            <h3>Outstanding applications</h3>
            <p>
              <% @unconfirmed_members.each do |member| %>
                <li><%= link_to member.username, member %> <%= link_to 'confirm', confirm_membership_path(user_id: member.id, beer_club_id: @beer_club.id), method: :post, class: 'btn btn-primary'%></li>
            <% end %>
            </p>
        <% end %>

        <% if @beer_club.memberships.count <= 1 %>
            <%= link_to 'end the membership and destroy the club', @membership, method: :delete, class:'btn btn-danger' %>
        <% else %>
            <%= link_to 'end the membership', @membership, method: :delete, class:'btn btn-danger' %>
        <% end %>
    <% else %>
        <%= form_for(@membership, method: :post) do |f| %>
            <%= f.hidden_field :beer_club_id %>
            <%= f.submit "join the club", class:'btn btn-success' %>
        <% end %>
    <% end %>
    <br>
    <br>
    <%= edit_and_destroy_buttons(@beer_club) %>
<% end %>
<br>
<%= link_to 'Back', beer_clubs_path, class: 'btn btn-default' %>