config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :beer_clubs

  resources :beers

  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  get 'places', to: 'places#index'
  post 'places', to: 'places#search'

  resources :places, only:[:index, :show]

  post 'places', to:'places#search'

  root 'breweries#index'

  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_banned', on: :member
  end
  resources :memberships, only: [:new, :create, :destroy] do
    post 'confirm', on: :member
  end

  get 'beerlist', to:'beers#list'

  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to:'breweries#list'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'
end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage
  require 'securerandom'

  has_secure_password

  has_many :ratings
  has_many :memberships
  has_many :confirmed_memberships, -> {where confirmed: true}, class_name: "Membership"
  has_many :unconfirmed_memberships, -> {where confirmed: [false, nil]}, class_name: "Membership"
  has_many :beer_clubs, through: :confirmed_memberships, source: :beer_club
  has_many :applied_memberships, through: :unconfirmed_memberships, source: :beer_club

  has_many :beers, through:  :ratings
  has_many :styles, through: :beers

  validates :username, uniqueness: true
  validates :username, length: { minimum: 3,
                                 maximum: 15 }
  validates_format_of :password, :with => /\A^(?=.*?[A-Z])(?=.*?[0-9]).{4,}$\Z/i

  def to_s
    "#{self.username}"
  end

  def self.top(n)
    sorted_by_rating_in_desc_order = self.all.sort_by{ |b| -(b.ratings.count||0) }
    sorted_by_rating_in_desc_order.take(n)
  end

  def favorite_beer
    return nil if ratings.empty?
    ratings.sort_by{ |r| r.score }.last.beer
  end

  def favorite(category)
    return nil if ratings.empty?
    category_ratings = rated(category).inject([]) do |set, item|
      set << {
          item: item,
          rating: rating_of(category, item) }
    end

    category_ratings.sort_by { |item| item[:rating] }.last[:item]
  end

  def favorite_brewery
    favorite(:brewery)
  end

  def favorite_style
    favorite(:style)
  end

  def rated(category)
    ratings.map{ |r| r.beer.send(category) }.uniq
  end

  def rating_of(category, item)
    ratings_of_item = ratings.select do |r|
      r.beer.send(category) == item
    end
    ratings_of_item.map(&:score).sum / ratings_of_item.count
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.id = auth["uid"]
      user.username = auth["info"]["nickname"]
      user.password = SecureRandom.random_number(36**12).to_s(36).rjust(12, "0")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :new, :create]
  before_action :ensure_that_is_admin, only: [:toggle_banned]

  def index
    @users = User.includes(:beers, :ratings).all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.ratings.each {|x| x.destroy}
    @user.memberships.each {|x| x.destroy}

    @user.destroy

    session[:user_id] = nil

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_banned
    user = User.find(params[:id])
    user.update_attribute :banned, (not user.banned)

    new_status = user.banned ? "banned" : "not banned"

    redirect_to :back, notice:"user banned status changed to #{new_status}"
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :banned)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if @user.new_record? %>
        <div class="field">
          <%= f.label :username %><br>
          <%= f.text_field :username %>
        </div>
    <% end %>

    <div class="field">
      <% if @user.new_record? %>
          <%= f.label :password %><br />
      <% else %>
          <%= f.label :new_password %><br />
      <% end %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation  %>
    </div>
    <div class="actions">
      <%= f.submit class:'btn btn-success' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class:'btn btn-default' %> |
<%= link_to 'Back', users_path, class:'btn btn-default' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<h1>Users</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Username</th>
    <th> rated beers </th>
    <th> total ratings </th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if current_user and current_user.admin and user.is_frozen? %>
              <span class="label label-info">account frozen</span>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:'btn btn-primary' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, class:'btn btn-default' %>

app/views/users/show.html.erb
<h1><%= @user.username %>
  <% if @user.banned %>
      <span class="label label-info">account frozen</span>
  <% end %>
</h1>

<% if not @user.ratings.empty? %>
    <p>Favorite style: <%= @user.favorite_style %></p>
    <p>Favorite brewery: <%= link_to @user.favorite_brewery.name, @user.favorite_brewery %></p>
<% end %>

<h3>Beer Clubs</h3>

<p>
<p><strong>member of</strong>
  <% @user.beer_clubs.each do |club| %>
      <%= link_to club.name, club %>
  <% end %>
</p>
<p><strong>applied membership of</strong>
  <% @user.applied_memberships.each do |club| %>
      <%= link_to club.name, club %>
  <% end %>
</p>
</p>

<% if not @user.ratings.empty? %>
    <h3>Ratings</h3>
    <p>has made
      <%= @user.ratings.count %>
      ratings with average of
      <%= @user.average_rating %>
    </p>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Beer</th>
        <th>Rating</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @user.ratings.each do |rating| %>
          <tr>
            <td><%= link_to rating.beer.name, rating.beer %></td>
            <td><%= rating.score %></td>
            <% if @user == current_user %>
                <td><%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

<% if current_user && current_user.admin && current_user != @user%>
    <% action = 'froze account'%>
    <% action = 'reactivate account' if @user.banned %>
    <%= link_to action, toggle_banned_user_path(@user.id), method: :post, class: 'btn btn-danger' %>
<% end %>

<br>
<br>

<% if current_user %>
    <%= edit_and_destroy_buttons(@user) %>|
<% end %>
    <%= link_to 'Back', users_path, class:'btn btn-default' %>