config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :beer_clubs

  resources :beers

  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  get 'places', to: 'places#index'
  post 'places', to: 'places#search'

  resources :places, only:[:index, :show]

  post 'places', to:'places#search'

  root 'breweries#index'

  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_banned', on: :member
  end
  resources :memberships, only: [:new, :create, :destroy] do
    post 'confirm', on: :member
  end

  get 'beerlist', to:'beers#list'

  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to:'breweries#list'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'
end

app/models/style.rb
class Style < ActiveRecord::Base
  include RatingAverage
  has_many :beers
  has_many :ratings, through: :beers

  def self.top(n)
    sorted_by_rating_in_desc_order = self.all.sort_by{ |b| -(b.average_rating||0) }
    sorted_by_rating_in_desc_order.take(n)
  end

  def to_s
    "#{self.name}"
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_is_admin, only: [:destroy]

  def index
    @styles = Style.all
  end

  def show
    @beers = Beer.all.to_a.keep_if {|beer| beer.style_id == @style.id }
  end

  def new
    @style = Style.new
  end

  def edit
  end

  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_style
      @style = Style.find(params[:id])
    end

    def style_params
      params.require(:style).permit(:name, :description)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing Style</h1>

<%= render 'form' %>

<%= link_to 'Show', @style, class:'btn btn-default'%> |
<%= link_to 'Back', styles_path, class:'btn btn-default' %>

app/views/styles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Styles</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @styles.each do |style| %>
      <tr>
        <td><%= style.name %></td>
        <td><%= style.description %></td>
        <td><%= link_to 'Show', style, class:'btn btn-info'%></td>
        <td><%= link_to 'Edit', edit_style_path(style), class:'btn btn-default' %></td>
        <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style', new_style_path, class:'btn btn-primary' %>

app/views/styles/new.html.erb
<h1>New Style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path, class:'btn btn-default' %>

app/views/styles/show.html.erb
<h1>
  <strong><%= @style.name %></strong>
</h1>

<p>
  <%= @style.description %>
</p>

<ul>
  <% @beers.each do |beer| %>
      <li> <%= beer %> </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_style_path(@style), class:'btn btn-default' %> |
<%= link_to 'Back', styles_path, class:'btn btn-default' %>